### ISSUE TITLE
JS / CSS assets do not build

### ISSUE THREAD

**Issue by gasman** [wagtail/docker-wagtail-develop#23]
On the current `main` branch (https://github.com/wagtail/wagtail/commit/8d0eff171718960a5cab6bf267ee8c1798dc3693 at time of writing), bringing up a developer instance as per the readme fails to build the CSS/JS assets from `/client` - as a result, visiting /admin gives an unstyled login page:

![Screenshot 2021-03-17 at 23 21 22](https://user-images.githubusercontent.com/85097/111551192-8f4d5500-8777-11eb-970a-825de56dd141.png)

Console output from the build process is attached.

[docker-wagtail-develop-db-setup.log](https://github.com/wagtail/docker-wagtail-develop/files/6160309/docker-wagtail-develop-db-setup.log)
[docker-wagtail-develop-setup.log](https://github.com/wagtail/docker-wagtail-develop/files/6160310/docker-wagtail-develop-setup.log)

**Comment by RealOrangeOne** [comment]
Just tried to reproduce this locally, and I can't.

Looking at the attached logs, the issue is that `docker-compose up` never starts the `frontend` container, and so the frontend never gets built. On my machine, the container does build, and run the build fine. If I run `setup-db.sh` _before_ the build has finished, then I get a result similar to this, even once the build has finished. Stopping everything and doing `docker-compose up` again fixes the issue, as the frontend is then actually rebuilt.

Given there's an implicit dependency here, perhaps users should be told to "wait a bit" whilst the frontend builds _then_ setup the DB?

**Comment by KalobTaulien** [comment]
I got them to build by manually running node commands outside of docker, which I know isn't the solution we're looking for — but it would unblock people for the time being.  

```bash 
cd wagtail/ && npm install && npm run build
```

Then re-run your container with `docker-compose up`

**Comment by saevarom** [comment]
@gasman can you make another attempt? I believe some of the major issue with the slowness of the frontend container starting process is fixed now.

**Comment by gasman** [comment]
@saevarom On a fresh installation I still get the server starting up before front-end assets are built, but now that the instructions in the readme cover that possibility and tell me how to fix it, that's good enough for me 👍 

(Only suggestion I'd make is that rather than saying "wait a few seconds for the frontend container to finish building", mention the specific message you're waiting for - "webpack compiled successfully in X ms".)

**Comment by saevarom** [comment]
Fair point, I've added that. Thank you @gasman
